# Generated by Django 4.1.7 on 2023-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TF', 'Traditional_Food'), ('SF', 'South_Indian_Food'), ('HK', 'Home_Kitchen'), ('FF', 'Famous_Food'), ('MK', 'Mummy_Kitchen'), ('HW', 'Health_is_Wealth')], max_length=2),
        ),
    ]
